name: Astro Site Check

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build Astro site
      id: astro-check
      run: |
        output=$(npm run astro check)
        echo "$output"
        errors_count=$(echo "$output" | grep -oP '(?<=- )[0-9]+(?= errors)')
        echo "::set-output name=errors-count::$errors_count"

    - name: Comment on PR if no errors
      if: steps.astro-check.outputs.errors-count == '0'
      run: |
        echo 'Ce Pull Request à bien était valider, un admin va merge le repo après validation sur la branche principale.' > comment.txt
        gh pr comment ${{ github.event.pull_request.number }} --repo ${{ github.repository }} --body-file comment.txt
      env:
        GH_TOKEN: ${{ secrets.BIG_TOKEN }}
